=== weglot/definitions/schemas/technologies.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "technologies.schema.json",
  "title": "Technology",
  "description": "This type of plugin applies the right technology_id to any resource that we need to translate later on. It also allows for defining 'proxy hosts', which Weglot connect uses to fake a domain and to replace hosts in the payloads. It's applied earlier in the process",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "title": {
      "title": "Technology name",
      "description": "Give a name to that technology",
      "$ref": "common.schema.json#/defs/PluginName"
    },
    "technology_id": {
      "$ref": "common.schema.json#/defs/TechnologyID"
    },
    "condition": {
      "$ref": "condition.schema.json#/defs/ConditionArray"
    },
    "proxyHosts": {
      "type": "array",
      "title": "Proxy hosts",
      "description": "Each entry is a hostname that Connect should proxy. Don't forget to create body replacements",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "settings": {
      "type": "array",
      "title": "Default settings to add to this technology",
      "description": "",
      "default": [],
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "condition": {
            "$ref": "condition.schema.json#/defs/ConditionArray"
          },
          "value": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "required": ["$schema", "title"],
  "defs": {
    "HTMLAction": {
      "type": "object",
      "title": "HTML Action",
      "description": "A set of conditions and resulting actions",
      "properties": {
        "conditions": {
          "type": "array",
          "minLength": 1,
          "items": {
            "$ref": "#/defs/ResourceCall"
          }
        },
        "actions": {
          "type": "array",
          "minLength": 1,
          "items": {
            "$ref": "#/defs/ResourceCall"
          }
        }
      }
    },
    "SearchConfig": {
      "type": "object",
      "properties": {
        "path": {
          "description": "Exact path, without parameters",
          "type": "string"
        },
        "parameter": {
          "type": "string",
          "description": "Usually 'q'"
        }
      }
    },
    "ResourceCall": {
      "type": "object",
      "properties": {
        "method": {
          "type": "string",
          "description": "Name of the method to call on the resource",
          "enum": ["has", "addWeglotJS"]
        },
        "arg": {}
      },
      "required": ["method", "arg"],
      "dependencies": {
        "method": {
          "oneOf": [
            {
              "properties": {
                "method": {
                  "const": "has"
                },
                "arg": {
                  "type": "string",
                  "description": "A CSS Selector that should return something"
                }
              }
            },
            {
              "properties": {
                "method": {
                  "const": "addWeglotJS"
                },
                "arg": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "string"
                  }
                }
              }
            }
          ]
        }
      }
    }
  }
}

=== weglot/definitions/technology-rules/technologies/squarespace.json
{
  "$schema": "../schemas/technologies.schema.json",
  "title": "Squarespace",
  "condition": [
    {
      "type": "HEADERS_SIGNATURE",
      "payload": {
        "headerName": "x-via",
        "regexMatch": "/^1\\.1 echo\\d{3}$/"
      }
    },
    {
      "type": "HEADERS_SIGNATURE",
      "payload": {
        "headerName": "x-contextid",
        "regexMatch": "/^\\w{8}\\/\\w{8}$/"
      }
    }
  ],
  "technology_id": 5,
  "proxyHosts": []
}

=== weglot/definitions/technology-rules/technologies/shopify.json
{
  "$schema": "../schemas/technologies.schema.json",
  "title": "Shopify",
  "condition": [
    {
      "type": "HEADERS_SIGNATURE",
      "payload": {
        "headerName": "x-shopify-stage"
      }
    }
  ],
  "technology_id": 2,
  "proxyHosts": ["feeds.datafeedwatch.com", "feeds.adwordsrobot.com"],
  "settings": [
    {
      "name": "Mollie checkout exclusion",
      "condition": [
        {
          "type": "PATH_MATCH",
          "payload": {
            "type": "MATCH_REGEX",
            "value": "/checkouts/([\\w]+)/forward"
          }
        }
      ],
      "value": [
        {
          "type": "excluded_blocks",
          "payload": [
            {
              "value": "#payment-form"
            }
          ]
        }
      ]
    },
    {
      "name": "Shopify Checkout page",
      "condition": [
        {
          "type": "PATH_MATCH",
          "payload": {
            "type": "MATCH_REGEX",
            "value": "/(\\d+)\/checkouts\/(\\w{32})"
          }
        }
      ],
      "value": [
        {
          "type": "whitelist",
          "payload": [
            {
              "value": "table.product-table .product__description__name"
            },
            {
              "value": "aside.sidebar #icons_text_section section div.description"
            }
          ]
        }
      ]
    }
  ]
}

=== weglot/definitions/rules/technologies/squarespace.server.json
{
  "$schema": "../../schemas/technologies.schema.json",
  "title": "Squarespace",
  "condition": [
    {
      "type": "RESPONSE_HEADER_MATCH",
      "payload": {
        "name": "x-via",
        "type": "MATCH_REGEX",
        "value": "/^1\\.1 echo\\d{3}$/"
      }
    },
    {
      "type": "RESPONSE_HEADER_MATCH",
      "payload": {
        "name": "x-contextid",
        "type": "MATCH_REGEX",
        "value": "/^\\w{8}\\/\\w{8}$/"
      }
    }
  ],
  "technology_id": 5,
  "proxyHosts": [],
  "settings": [
    {
      "name": "Password protected page",
      "value": [
        {
          "type": "disable_cookie_encoding",
          "payload": ["Locked"]
        }
      ]
    },
    {
      "name": "Sale price",
      "value": [
        {
          "type": "merged_selectors_remove",
          "payload": [{ "value": ".product-price .original-price" }]
        }
      ]
    },
    {
      "name": "Don't proxify scheduling blocks",
      "value": [
        {
          "type": "excluded_blocks",
          "payload": [
            {
              "value": ".acuity-block iframe[data-iframe-translate]"
            }
          ]
        }
      ]
    },
    {
      "name": "Don't translate request id on 404",
      "condition": [
        {
          "type": "PATH_MATCH",
          "payload": {
            "type": "IS_EXACTLY",
            "value": "/404"
          }
        }
      ],
      "value": [
        {
          "type": "excluded_blocks",
          "payload": [
            {
              "value": "body > footer"
            }
          ]
        }
      ]
    }
  ]
}

=== weglot/definitions/rules/technologies/wix.json
{
  "$schema": "../../schemas/technologies.schema.json",
  "title": "Wix",
  "technology_id": 6,
  "condition": [
    {
      "type": "HEADER_MATCH",
      "payload": {
        "name": "x-wix-request-id",
        "type": "START_WITH",
        "value": ""
      }
    }
  ],
  "proxyHosts": ["siteassets.parastorage.com"]
}

=== weglot/definitions/rules/technologies/squarespace.json
{
  "$schema": "../schemas/technologies.schema.json",
  "title": "Squarespace",
  "condition": [
    {
      "type": "HEADERS_SIGNATURE",
      "payload": {
        "headerName": "x-via",
        "regexMatch": "/^1\\.1 echo\\d{3}$/"
      }
    },
    {
      "type": "HEADERS_SIGNATURE",
      "payload": {
        "headerName": "x-contextid",
        "regexMatch": "/^\\w{8}\\/\\w{8}$/"
      }
    }
  ],
  "technology_id": 5,
  "proxyHosts": [],
  "settings": [
    {
      "name": "Password protected page",
      "value": [
        {
          "type": "disable_cookie_encoding",
          "payload": [ "Locked" ]
        }
      ]
    },
    {
      "name": "Sale price",
      "value": [
        {
          "type": "merged_selectors_remove",
          "payload": [ { "value": ".product-price .original-price" } ]
        }
      ]
    }
  ]
}

=== weglot/definitions/rules/technologies/squarespace.client.json
{
  "$schema": "../../schemas/technologies.schema.json",
  "title": "Squarespace",
  "technology_id": 5,
  "proxyHosts": [],
  "settings": [
    {
      "name": "Squarespace default settings for all pages",
      "value": [
        {
          "type": "dynamics",
          "payload": [
            {
              "value": "#sqs-cart-container"
            },
            {
              "value": "#checkout"
            },
            {
              "value": ".sqs-widgets-confirmation"
            },
            {
              "value": ".video-player"
            },
            {
              "value": ".jdgm-widget"
            },
            {
              "value": ".calendar-block"
            },
            {
              "value": ".opentable-v2-block"
            },
            {
              "value": ".blog-item-comments"
            }
          ]
        },
        {
          "type": "excluded_blocks",
          "payload": [
            {
              "value": "body.sqs-is-page-editing"
            }
          ]
        },
        {
          "type": "merged_selectors_remove",
          "payload": [
            {
              "value": ".plyr__menu__container"
            },
            {
              "value": ".comment-btn-wrapper"
            },
            {
              "value": ".product-price .original-price"
            }
          ]
        },
        {
          "type": "extra_definitions",
          "payload": [
            {
              "type": 1,
              "selector": ".variant-select-wrapper",
              "attribute": "data-text"
            }
          ]
        }
      ]
    },
    {
      "name": "Squarespace settings for proxy integration",
      "condition": [
        {
          "type": "INTEGRATION",
          "payload": "proxy"
        }
      ],
      "value": [
        {
          "type": "dynamics",
          "payload": [
            {
              "value": ".sqs-add-to-cart-button.cart-adding"
            },
            {
              "value": ".sqs-add-to-cart-button.cart-added"
            }
          ]
        },
        {
          "type": "excluded_blocks",
          "payload": [
            {
              "value": ".comment-body"
            }
          ]
        }
      ]
    },
    {
      "name": "Squarespace settings for javascript integration",
      "condition": [
        {
          "type": "INTEGRATION",
          "payload": "javascript"
        }
      ],
      "value": [
        {
          "type": "dynamics",
          "payload": [
            {
              "value": "[data-dynamic-strings]"
            },
            {
              "value": ".sqs-add-to-cart-button"
            },
            {
              "value": ".variant-select-wrapper"
            }
          ]
        },
        {
          "type": "excluded_blocks",
          "payload": [
            {
              "value": ".animation-segment-wrapper"
            },
            {
              "value": ".animation-segment-parent-hidden > *"
            }
          ]
        }
      ]
    },
    {
      "name": "Squarespace settings for cart page",
      "condition": [
        {
          "type": "DOM_CONTAINS",
          "payload": {
            "selector": "#sqs-cart-root"
          }
        }
      ],
      "value": [
        {
          "type": "excluded_blocks",
          "payload": [
            {
              "value": "#sqs-cart-container [class*=subtotalPrice]"
            },
            {
              "value": "#sqs-cart-container .cart-container .item-price"
            }
          ]
        },
        {
          "type": "force_translation",
          "payload": ["#sqs-cart-container"]
        }
      ]
    },
    {
      "name": "Squarespace settings for checkout page",
      "condition": [
        {
          "type": "DOM_CONTAINS",
          "payload": {
            "selector": "#sqs-standard-checkout"
          }
        }
      ],
      "value": [
        {
          "type": "excluded_blocks",
          "payload": [
            {
              "value": "#checkout span.money"
            },
            {
              "value": "#checkout [data-test*=incomplete] [class^=PaymentCard-container]"
            },
            {
              "value": "#checkout [data-test*=incomplete] [class^=CustomerAddress-container]"
            },
            {
              "value": "#checkout [class^=CustomerInfoSection-email]"
            },
            {
              "value": "#checkout [class^=GoogleResultsList]"
            }
          ]
        },
        {
          "type": "force_translation",
          "payload": ["#checkout"]
        }
      ]
    },
    {
      "name": "Squarespace settings for order status page",
      "condition": [
        {
          "type": "DOM_CONTAINS",
          "payload": {
            "selector": "#order-status-page-root"
          }
        }
      ],
      "value": [
        {
          "type": "excluded_blocks",
          "payload": [
            {
              "value": "#order-status-page-root #order-number"
            },
            {
              "value": "#order-status-page-root h2 + div > p"
            }
          ]
        },
        {
          "type": "force_translation",
          "payload": ["#order-status-page-root"]
        }
      ]
    },
    {
      "name": "Disable Connect on the Squarespace site admin area",
      "condition": [
        {
          "type": "HOST_MATCH",
          "payload": {
            "type": "END_WITH",
            "value": "squarespace.com"
          }
        }
      ],
      "value": [
        {
          "type": "forceDisableConnect",
          "payload": true
        }
      ]
    }
  ]
}
